name: build-and-boot

on:
  push:
    branches: [ main, staging ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Instalar Dependencias
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq make nasm grub-pc-bin xorriso qemu-system-x86

      - name: Build Kernel e Userland
        run: |
          make -C OvsbMk clean
          make -C OvsbMk all
          make -C OvsbMk iso

      - name: Valida Kernel ELF
        run: |
          file OvsbMk/build/kernel.elf | grep -q ELF && echo "Kernel ELF OK"

      - name: Boot test headless 
        timeout-minutes: 2
        run: |
      
          timeout 10s qemu-system-x86_64 -cdrom OvsbMk/OvsbMkM.iso -display none -serial stdio || true
